RentApp/RentApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('search/',include('search.urls')),

]



if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

RentApp/app1/urls.py
from django.contrib import admin
from django.urls import path,include
from app1 import views
app_name="app1"


urlpatterns = [path('',views.home,name="home"),
               path('items/',views.items,name="items"),
               path('upload/',views.upload,name="upload"),
               path('category/<n>',views.category,name="category"),
               path('register/',views.register,name="register"),
               path('login/',views.user_login,name="login"),
               path('logout/',views.user_logout,name="logout"),
               path('itemdetail/<int:pk>/', views.item_detail, name='itemdetail'),
               path('useruploads/',views.user_uploads,name="useruploads"),
               path('update/<int:pk>',views.update,name="update"),
               path('deletepost/<int:pk>',views.post_delete,name="delete"),
               path('favourite/<int:pk>/', views.favourite, name='fav'),
               path('fav/',views.favor_view,name="fav_view"),
               path('request_form/<int:pk>',views.request_form,name="requestform"),
               path('view_booking_requests/',views.view_booking_requests,name="bookreq"),
               path('reply-booking-request/<int:pk>/', views.reply_booking_request, name='reply_booking_request'),
               path('view_your_requests',views.view_request,name="viewreq")




]

RentApp/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
app_name="search"


urlpatterns = [

    path('item/',views.search,name="search"),


]

RentApp/search/models.py
from django.db import models

# Create your models here.

RentApp/search/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import  render,redirect
from app1.models import Item
from django.db.models import Q



def search(request):
    query = ""
    item = None
    if (request.method == "POST"):
        query = request.POST['q']
        if (query == ""):
            item = Item.objects.all()
        else:
            item = Item.objects.filter(
                Q(name__icontains=query) | Q(category__name__icontains=query))

    return render(request, 'search.html', {'query': query, 'item': item})

RentApp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}home{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet"  href="{% static 'css/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css">



    {% block extra_css %}{% endblock %}


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>


<body>
    <nav id="navbar" class="navbar navbar-expand-lg navbar-light fs-5 fixed-top " style="background-color:#0343a8;box-shadow:0px 0px 10px rgba(0, 0, 0, 0.7);">
  <div class="container-fluid ">
    <a class="navbar-brand text-white me-5 ms-3" href="#"><img src="{% static 'images/logo.png' %}" height="68px" width="150px" class="rounded"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse t" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        <li class="nav-item ">
          <a class="nav-link active text-white ms-5 me-5" aria-current="page" href="{%url 'app1:home'%}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Collections
          </a>
          <ul class="dropdown-menu ms=-5" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item " href="{%url 'app1:category' i.name%}">{{i.name}}</a></li>
               {% endfor %}
              <li><a class="dropdown-item" href="{%url 'app1:items'  %} ">All</a></li>
          </ul>
        </li>
           <li class="nav-item ">
          <a class="nav active text-white p-2 ms-5 btn btn-dark text-center" aria-current="page" href="{%url 'app1:upload'  %}">Upload Your Item</a>
        </li>
          {% else %}
          <li class="nav-item ">
          <a class="nav-link active text-white ms-5 me-5" aria-current="page" href="{%url 'app1:register'%}">register</a>
        </li>
        {% endif %}
      </ul>
        {% if user.is_authenticated %}
      <form class="d-flex m-2" method="POST" action="{% url 'search:search'%} " >
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        <a class="icon" href="{%url 'app1:fav_view' %}" ><i class="fa-solid fa-heart fs-5  p-3 "></i></a>
        <a class="icon" href="{% url 'app1:useruploads' %}" ><i class="fa-solid fa-user m-3 fs-5  " ></i></a>
        <a class=""  href="{%url 'app1:logout'%}"><i class="icon fa-solid fa-right-from-bracket fs-3 p-3 "></i></a>

        {% endif %}
    </div>
  </div>
</nav>

{% block content %}



{% endblock %}
<footer class="bg-body-tertiary text-center text-lg-start p2-5 mt-2 fixed-bottom">
  <div class="text-center text-light p-3 mt-5" style="background-color: #0343a8;box-shadow:0px 0px 10px rgba(0, 0, 0, 0.7);">
    © 2024 Copyright:
    <a class="text-body" href="#"><b>Rento</b></a>
  </div>
</footer>

<script>
    AOS.init({
        duration: 1000,  // Animation duration in milliseconds
        offset: 200,     // Offset (in pixels) from the top of the window to trigger animations
        easing: 'ease',  // Easing function for animations (e.g., 'ease', 'ease-in-out', 'linear')
        once: true       // Whether to only animate elements once (true) or every time they enter the viewport (false)
    });
</script>

</body>
</html>

RentApp/templates/booking_requests.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid mb-5 pb-5" style="padding-top: 125px;">
    <div class="row">
        {% if not booking_requests%}
        <p class="text-center">Currently no request available</p>
        {%endif%}
        {% for request in booking_requests %}
            <div class="col-md-4 pb-4 mb-4">
                <div class="card">
                    <img src="{{ request.item.image.url }}" class="card-img-top" style="width: 100%; max-height: 150px; object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title">{{ request.item.name }}</h5>
                        <p class="card-text">
                            <strong>Requested by:</strong> {{ request.user.username }}<br>
                            <strong>Email:</strong> {{ request.email }}<br>
                            <strong>Requested Date:</strong> {{ request.requested_date }}<br>
                        </p>
                        <form action="{% url 'app1:reply_booking_request' request.id %}" method="post">
                            {% csrf_token %}
                            <div class="d-flex justify-content-between">
                                {% if request.booking_status == 'accepted' %}
                                    <strong class="text-success">Accepted</strong>
                                {% else %}
                                    <button type="submit" name="status" value="accepted" class="btn btn-success">Accept</button>
                                {% endif %}
                                {% if request.booking_status == 'not_available' %}
                                    <strong class="text-danger">Rejected</strong>
                                {% else %}
                                    <button type="submit" name="status" value="not_available" class="btn btn-danger">Reject</button>
                                {% endif %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

RentApp/templates/error_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>404 ERROR ITEM NOT FOUND</h1>
</body>
</html>

RentApp/templates/favo.html
{% extends 'base.html' %}
{% load static %}
{% block title %}View Liked{% endblock %}

{% block content %}
<div class="container-fluid" style="padding-top: 125px;" >

<div class="row">
  {% for i in f %}
  <div class="col-lg-3 col-md-4 col-sm-6  mb-5 " data-aos="fade-left">
<div class="product-card mt-2 mb-4 ms-4" style="background-color:white;border-radius:10px;box-shadow:0 4px 8px rgba(0,0,0,0.1);transition:all .5s;overflow:hidden;width:300px;">

  <div class="product-image " >
    <img src="{{i.item.image.url}}" style="width:100%;height:200px;background-size:cover;" class="image-hover">
  </div>
  <div class="product-info">

    <div class="product-name p-2 text-center"><b>{{i.item.name}}</b></div>
    <div class="product-price ps-2 text-center">{{i.item.price}} per day</div>
    <div class="product-upload pt-2 ps-2 text-center"></div>
    <center><a href="{%url 'app1:itemdetail' i.item.id %}" class="btn btn-info m-3">Details</a></center>
  </div>
</div>
</div>
{% endfor %}

</div>






</div>

{%endblock%}

RentApp/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block content %}


<div class="container-fluid mt-5 pt-5" >
{% if user.is_authenticated %}
    <!-- Modal -->
<h1 data-aos="fade-down" class="text-center">Welcome {{user.first_name}} {{user.last_name}} !!</h1>
{% endif %}

  <div class="row mt-5" data-aos="fade-down">

    <div class="col-md-5 ms-3">

    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/vehicle.jpeg' %}" class="d-block w-100" alt="..." height="400px" width="70%">

    </div>
    <div class="carousel-item "  style=" box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);">
      <img src="{% static 'images/electr.jpg' %}" class="d-block w-100" alt="..." height="400px" width="400px">

    </div>
    <div class="carousel-item">
      <img src="{%static 'images/house1.avif' %}" class="d-block w-100" alt="..." height="400px" width="400px">

    </div>
  </div>

      </div>


  </div>

<div class="col-md-6 ms-5" style="display:flex;justify-content:center;box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);">
    <div>
        <center><h1 data-aos="fade-left" class="m-5">Discover Rento!!!</h1>
        <div>
            <p class="ms-5">Welcome to <b>Rento</b>, your one-stop destination for all your rental needs! <br>Whether you're searching for a cozy apartment, a stylish car, or electronic items, Rento has you covered. With a vast array of rental listings uploaded by users just like you, finding your perfect rental experience has never been easier.</p>
        </div></center>
    </div>
</div>
</div>

    <div class="mt-4" >
        <h1 class="mt-4" data-aos="fade-left" style="display:flex;justify-content:center;">Our Collections</h1>
    </div>
    <div data-aos="fade-left" class="collection_div m-5" style="box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);">
        <div class="row m-5" style="display:flex;justify-content:center;">
            <div class="collection-list col-md-4 ">
                <div>
                <i class="fa-solid fa-car-side" ></i>
                <h2>Vehicles</h2>
                <p >Explore our collection of vehicles available for rent  and discover the perfect ride for your next adventure.</p>
                <a  href="{%url 'app1:category' 'Vehicles' %}" class="btn btn-info mt-4" style="margin-bottom:12px;">Learn more!!</a>
                </div>
            </div>

            <div class="collection-list col-md-4  ">
                <div>
               <i class="fa-solid fa-building"></i>
               <h2>Buildings,Apartment,House...</h2>
                <p >Discover the perfect rental solution for your lifestyle,whether it's a spacious house, a modern apartment, or a prestigious building in the heart of the city.</p>
                <a href="{%url 'app1:category' 'buildings' %}" class="btn btn-info " style="margin-top: 2px;">Learn more!!</a>
             </div>
            </div>

            <div class="collection-list col-md-4 ">
                <div>
                <i class="fa-solid fa-bolt"></i>
                <h2>Electronics</h2>
                <p>Experience the convenience of renting good-quality electronics items for your desired purpose</p>
                <a href="{%url 'app1:category' 'Electronics' %}" class="btn btn-info ">Learn more!!</a>
                </div>
            </div>

                <div class="collection-list col-md-4 " >
                    <div>
                    <i class="fa-solid fa-gear"></i>
                    <h2>Others</h2>
                    <p>Explore our wide range of rental options beyond the usual, from specialty equipment to unique experiences, we have everything <br>you need to make your rental experience extraordinary.</p>
                    <a href="{%url 'app1:category' 'others' %}" class="btn btn-info " style="margin-top: 5px;">Learn more!!</a>
                    </div>
                </div>
        </div>

        <div class="browse " style="display:flex;align-items:center;justify-content:center;" >
            <a href="{%url 'app1:items'%}" class="btn btn-info text-light mb-5" >Browse More !!</a>
        </div>
    </div>

</div>
{% endblock %}

RentApp/templates/itembycat.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid mb-5 pb-5 " style="padding-top: 125px;" data-aos="fade-left">
            <div class="cat-item">
                <div class="banner">
                    <img src="{{c.image.url}}" alt="...">
                    <div class="banner-text">
                        <h3 class="ms-5">{{c.name}}</h3>
                        <p>{{c.desc}}</p>
                    </div>
                </div>
            </div>


<div class="row">
  {% for i in item %}
  <div class="col-lg-3 col-md-4 col-sm-6 mt-4 mb-5">
<div class="product-card mt-5 mb-4 ms-5" style="background-color:white;border-radius:10px;box-shadow:0 4px 8px rgba(0,0,0,0.1);transition:all .5s;overflow:hidden;width:300px;">

  <div class="product-image " >
    <img src="{{i.image.url}}" style="width:100%;height:200px;background-size:cover;" class="image-hover">
  </div>
  <div class="product-info">

    <div class="product-name p-2 text-center"><b>{{i.name}}</b></div>
    <div class="product-price ps-2 text-center">{{i.price}} per day</div>
    <div class="product-upload pt-2 ps-2 text-center"></div>
    <center><a href="{%url 'app1:itemdetail' i.pk %}" class="btn btn-info m-3">Details</a></center>
  </div>
</div>
    </div>
{% endfor %}
</div>
</div>






{% endblock %}

RentApp/templates/itemdetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid " style="padding-top: 125px;">

 <section class="main-wrap">
        <div class="row me-5">

            <div class="image-gallery col-md-5 ms-5 me-3" >
                <img src="{{p.image.url}}" id="productImg" alt="" style="height:400px;width:100%;padding-top: 100px;">
                </div>
            <div class="product-details col-md-5 " style="padding-top: 100px;">
                <div class="details pt-2 ">
                    <h2>{{p.name}}</h2>
                    <h6>{{p.desc}}</h6>
                <div class="mt-2 mb-2">
                    {% if f %}
                    <a href="{% url 'app1:fav' p.pk %}" style="text-decoration:none;color:red;"><i class="fa-solid fa-heart   fs-5"></i></a>

                    {% else %}

                    <a href="{% url 'app1:fav' p.pk %}" style="text-decoration:none;color:red;"><i class="fa-regular fa-heart    fs-5"></i></a>

                    {% endif %}
                </div>

                    <h4 class="d-inline-block">Price: {{ p.price }}</h4><h5 class="d-inline-block"> /- &nbsp;&nbsp;per day</h5>

                    <h4>Contact No : {{p.phone}}</h4>

                     <p><i>Posted date : {{p.created}}</i></p>
                </div>
                {% if p.user == request.user %}

                <p>uploaded by you</p>
            </div>
        </div>
    </section>
                {% else %}
                <div class="sub-btn">
                    <a href="" data-bs-toggle="modal" data-bs-target="#bookingModal" class="btn btn-info ">Check availability</a>
                </div>
            </div>
        </div>
    </section>

{% endif %}


<!-- Modal -->
<div class="modal fade" id="bookingModal" tabindex="-1" aria-labelledby="bookingModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="bookingModalLabel">Check availability</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Your form goes here -->
                <form id="bookingForm" method="POST" action="{% url 'app1:requestform' p.pk %}">
                    {% csrf_token %}
                    <!-- Form fields -->
<!--                    <div class="mb-3">-->
<!--                        <input type="text" name="name" placeholder="Your Name" class="form-control" required>-->
<!--                    </div>-->
                    <div class="mb-3">
                        <input type="email" name="email" placeholder="Your Email" class="form-control" required>
                    </div>
                    <div class="mb-3">
                        <input type="date" name="date" placeholder="Booking date" class="form-control" required>
                    </div>
                    <div id="formMessage" class="alert d-none"></div> <!-- Success/Error message container -->
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('bookingForm').addEventListener('submit', function(event) {
        // Show success message
        var formMessage = document.getElementById('formMessage');
        formMessage.innerHTML = 'Form submitted successfully!';
        formMessage.classList.remove('alert-danger'); // Remove any error classes
        formMessage.classList.add('alert-success'); // Add success class
        formMessage.classList.remove('d-none'); // Show the message

        // Allow the form to submit after showing the success message
        setTimeout(function() {
            formMessage.classList.add('d-none'); // Hide the message again
            event.target.submit(); // Manually submit the form
        }, 20000); // Adjust the delay (in milliseconds) as needed
    });
</script>

{% endblock %}

RentApp/templates/items.html
{% extends 'base.html' %}
{% load static %}
{% block title %}All Items{% endblock %}

{% block content %}
<div class="container-fluid mb-5 pb-5" style="padding-top: 125px;" >

    <div id="carouselExampleCaptions" class="carousel slide mb-5" data-bs-ride="carousel" data-aos="fade-down">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="banner carousel-overlay">
                    <img src="{% static 'images/vehicles.jpg' %}"  alt="...">
                    <div class="banner-text carousel-caption">
                        <h3 class="ms-5">Vehicles</h3>
                        <p>Explore our collection of vehicles available for rent  and discover the perfect ride for your next adventure.</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="banner carousel-overlay">
                    <img src="{% static 'images/electronics.jpg' %}"  alt="...">
                    <div class="banner-text carousel-caption">
                        <h3 class="ms-5">Electronics</h3>
                        <p>Experience the convenience of renting good-quality electronics items for your desired purpose</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="banner carousel-overlay">
                    <img src="{% static 'images/buildong.jpg' %}" alt="...">
                    <div class="banner-text carousel-caption">
                        <h3 class="ms-5">Buildings,Apartment,House...</h3>
                        <p>Discover the perfect rental solution for your lifestyle,whether it's a spacious house, a modern apartment, or a prestigious building in the heart of the city</p>
                    </div>
                </div>
            </div>
        </div>
    </div>



<div class="row">
  {% for i in items %}
  <div class="col-lg-3 col-md-4 col-sm-6  mb-5 " data-aos="fade-left">
<div class="product-card mt-2 mb-4 ms-4" style="background-color:white;border-radius:10px;box-shadow:0 4px 8px rgba(0,0,0,0.1);transition:all .5s;overflow:hidden;width:300px;">

  <div class="product-image " >
    <img src="{{i.image.url}}" style="width:100%;height:200px;background-size:cover;" class="image-hover">
  </div>
  <div class="product-info">

    <div class="product-name p-2 text-center"><b>{{i.name}}</b></div>
    <div class="product-price ps-2 text-center">{{i.price}} per day</div>
    <div class="product-upload pt-2 ps-2 text-center"></div>
    <center><a href="{%url 'app1:itemdetail' i.pk %}" class="btn btn-info m-3">Details</a></center>
  </div>
</div>
    </div>
{% endfor %}
</div>



</div>



{% endblock %}

RentApp/templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block extra_css %}
<link rel="stylesheet"  href="{% static 'css/registerlogin.css' %}">
{% endblock %}




{% block content %}
<div class="container-fluid" style="padding-top: 100px;margin-bottom:50px;" data-aos="fade-left">
  <div class="container mt-5 mb-3">

    <div class="login form pt-5">
      <header>Login</header>

    {% if failed %}
    <p class="alert alert-danger">{{ failed }}</p>
    {% endif %}

      <form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        <input type="text" placeholder="Enter your username" name="username">
        <input type="password" placeholder="Enter your password" name="password">
        <input type="submit" class="btn btn-info" value="Login">
      </form>

      <div class="signup">
        <span class="signup">Don't have an account?
         <a href="{%url 'app1:register' %} ">Signup</a>
        </span>
      </div>
    </div>

</div>
  </div>


{% endblock %}

RentApp/templates/register.html
{% extends 'base.html' %}
{% load static %}


{% block extra_css %}
<link rel="stylesheet"  href="{% static 'css/registerlogin.css' %}">
{% endblock %}




{% block content %}
<div class="container-fluid pb-5" style="padding-top: 30px;margin-bottom:50px;" data-aos="fade-left">
  <div class="container mb-5 pb-5 pt-3" >

      {% if success %}
    <p class="alert alert-success ">{{ success }} Click here to <a href="{%url 'app1:login' %}" class="alert-link">Login</a></p>
    {% endif %}

    {% if failed %}
    <p class="alert alert-danger fs-5 ">{{ failed }}</p>
    {% endif %}

<!--/******registration****/-->
    <div class="registration form mt-2 ">
      <header>Signup</header>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" placeholder="Enter your firstname" name="fn" required>
        <input type="text" placeholder="Enter your lastname" name="ln" required>
        <input type="text" placeholder="Enter a Username" name="un" required>
        <input type="email" placeholder="Enter your email" name="email" required>
        <input type="password" placeholder="Create a password" name="pass" required>
        <input type="password" placeholder="Confirm your password" name="cpass" required>

        <input type="submit" class="btn btn-info " value="Signup">
      </form>
      <div class="signup">
        <span class="signup">Already have an account?
         <a href="{% url 'app1:login' %}">Login</a>
        </span>
      </div>
    </div>

  </div>


</div>
{% endblock %}

RentApp/templates/useruploads.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User Uploads{% endblock %}

{% block content %}
<div class="container-fluid" style="padding-top: 125px;">

  <h3 class="text-center">View Booking Status and Request</h3>
  <div style="">
    <div class="text-center">
       <a href="{%url 'app1:viewreq' %}" ><button class="btn btn-primary m-4">View Your Requests Status</button></a>
      <a href="{%url 'app1:bookreq'%}"><button class="btn btn-danger m-4 ">View Recived Request</button></a>


    </div>

  </div>

<div class="row">
  <h3 class="text-center p-4">Your Uploads</h3>
  {% for i in item %}
  <div class="col-lg-3 col-md-4 col-sm-6  mb-5 " data-aos="fade-left">
<div class="product-card mt-2 mb-4 ms-4" style="background-color:white;border-radius:10px;box-shadow:0 4px 8px rgba(0,0,0,0.1);transition:all .5s;overflow:hidden;width:300px;">

  <div class="product-image " >
    <img src="{{i.image.url}}" style="width:100%;height:200px;background-size:cover;" class="image-hover">
  </div>
  <div class="product-info">
    <div class="product-name p-2 text-center"><b>{{i.name}}</b></div>
    <div class="product-price ps-2 text-center">{{i.price}} per day</div>
    <div class="product-upload pt-2 ps-2 text-center d-flex justify-content-around">
    <a href="{%url 'app1:delete' i.id %}" class="btn btn-danger  mt-3 mb-3 ">Delete Post</a>
<!-- <a href="{% url 'app1:delete' pk=i.pk %}"  class="btn btn-danger  mt-3 mb-3 ">Delete Post</a>-->
      <a href="{%url 'app1:itemdetail' i.pk %}" class="btn btn-success  m-3">Details</a>
    <a href="{% url 'app1:update' i.id %}" class="btn btn-success me-2 mt-3 mb-3 ">Edit Post</a>
      </div>
  </div>
</div>
    </div>
{% endfor %}
</div>



</div>



{% endblock %}